### ISSUE TITLE
tf_result_explanations error

### ISSUE THREAD

**Issue by sngholee** [Dowell-Lab/DAStk#37] opened 2024-01-03 23:32 UTC
Hello,

I ran process_atac on my ATAC seq files, and then differential_md_score. Those seem to have run fine. But when I run tf_result_explanations, I get the below error. I used the HOCOMOCO preprocessed mm10 motifs file. I would appreciate any help on getting this to work.

`Traceback (most recent call last):
  File "/public/home/slee393/miniconda3/bin/differential_md_score", line 8, in <module>
    sys.exit(differential_md_score())
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/DAStk/__init__.py", line 12, in differential_md_score
    d.main()
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/DAStk/differential_md_score.py", line 273, in main
    adjust_text(texts, force_points=1, expand_points=(2,2), expand_text=(2,2), arrowprops=dict(arrowstyle="-", lw=1, color='black', alpha=0.8))
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/adjustText/__init__.py", line 567, in adjust_text
    transform = texts[0].get_transform()
                ~~~~~^^^
IndexError: list index out of range`

**Comment by ignaciot** [comment] 2024-01-11 22:54
Hi there, this seems like a duplicate of a recent usability issue that was fixed (this is most likely because none of the motifs presents a significant p-value with the default threshold which is rather stringent, so you can try passing a different p-value threshold with the corresponding command line argument).

**Closed as not planned by ignaciot** 2024-01-11 22:54 UTC

**Comment by ignaciot** [comment] 2024-01-11 22:56
Duplicate of [Issue #35](https://github.com/Dowell-Lab/DAStk/issues/35).
